### ISSUE TITLE
VisSat Error-after bundle cameras

### ISSUE THREAD

**Issue by dbonafilia** [Kitware/Danesfield#24]
Hi! I'm trying to run the generate_point_cloud section of the code using VisSat for the Jacksonville Core3D data. But 
it seems to error out in self.run_colmap_sfm_perspective() because the after_bundle_cameras data never populates. I'm using the docker imager. Here's the full error:

```
Traceback (most recent call last):
  File "/VisSatSatelliteStereo/stereo_pipeline.py", line 511, in <module>
    pipeline.run()
  File "/VisSatSatelliteStereo/stereo_pipeline.py", line 115, in run
    self.run_colmap_sfm_perspective()
  File "/VisSatSatelliteStereo/stereo_pipeline.py", line 346, in run_colmap_sfm_perspective
    colmap_sfm_perspective.run_sfm(work_dir, sfm_dir, init_camera_file, weight)
  File "/VisSatSatelliteStereo/colmap_sfm_perspective.py", line 95, in run_sfm
    after_bundle_params = after_bundle_cameras[img_name]
KeyError: '0000_WV03_14OCT05_160138-P1BS-500648062040_01_P001.png'
Traceback (most recent call last):
  File "/danesfield/tools/generate_point_cloud.py", line 51, in <module>
    main(sys.argv[1:])
  File "/danesfield/tools/generate_point_cloud.py", line 32, in main
    subprocess.run(cmd_args, check=True)
  File "/opt/conda/envs/core3d/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/bin/bash', '-c', 'source /opt/conda/etc/profile.d/conda.sh && conda activate vissat                 && python3 /VisSatSatelliteStereo/stereo_pipeline.py --config_file /home/derrickbonafilia/config.json']' returned non-zero exit status 1.
ERROR:root:---- Error on step: VisSat. Aborting! ----

```
and here's the config for the VisSat:

`{'dataset_dir': '/home/derrickbonafilia/spacenet/WV3/PAN/', 'work_dir': './', 'bounding_box': {'zone_number': 17, 'hemisphere': 'N', 'ul_easting': 435525, 'ul_northing': 3355525, 'width': 1402.0, 'height': 1448.0}, 'steps_to_run': {'clean_data': True, 'crop_image': True, 'derive_approx': True, 'choose_subset': True, 'colmap_sfm_perspective': True, 'inspect_sfm_perspective': False, 'reparam_depth': True, 'colmap_mvs': True, 'aggregate_2p5d': True, 'aggregate_3d': True}, 'alt_min': -30.0, 'alt_max': 120.0}
`

Thanks for any help you can give!

**Comment by mleotta** [comment]
Are you running it with `nvidia-docker`?

**Comment by dbonafilia** [comment]
Yes, I'm running it with:     
```
nvidia-docker run -it --rm --gpus all --shm-size 8G\
     -v /$DATA/CORE3D:/mnt -v $HOME:/home/$USER -v /$WORK:/work\
     kitware/danesfield /bin/bash

```

**Comment by mleotta** [comment]
I've haven't been running this myself, so I'm not sure if others have encountered this.  @jacobderosa or @borovik135 have you seen this issue before?

**Comment by borovik135** [comment]
I focused mostly on the imageless pipeline, thus no recollection of this or similar error.

**Comment by jacobderosa** [comment]
I don't know exactly what the issue is but I suspect something went wrong during the derive_approx step or during the SIFT matching early in the colmap_sfm step. Check the log files

**Comment by borovik135** [comment]
Could it be that we are running out of RAM with --SiftExtraction.max_image_size 10000? default is 3200.

**Comment by dbonafilia** [comment]
Wondering if maybe there's a CUDA issue happening somewhere. If there a suggested/required CUDA version for this?
