### ISSUE TITLE
Running Danesfield - Demo

### ISSUE THREAD

**Issue by NourSoltani** [Kitware/Danesfield#46]
![screenshot](https://user-images.githubusercontent.com/57375012/195362183-56c51873-cd72-42f6-81fa-fac2f0ffdbb5.png)
Greetings!
First of all, I would to thank you for sharing the demonstration.. It is helping a lot.
And also, I would like to apologize since I have been asking many questions the last period. 
Well, I have downloaded a part of data (more specifically the Jacksonville data), the docker image...etc.
But whenever I try to run the script, it always prompt this message

Is there any idea for what could be the cause of that?

**Comment by mleotta** [comment]
@jacobderosa can you take a look at this and respond?

**Comment by jacobderosa** [comment]
@NourSoltani It doesn't look like your input_Jacksonville.ini is in your config directory (that you mounted to /configs)

**Comment by NourSoltani** [comment]
@jacobderosa Well It exists in the /configdir folder which i have mounted to /configs
![config](https://user-images.githubusercontent.com/57375012/195385331-4b446cac-2bd4-4ab2-bfcf-88185b381e1d.png)

**Comment by NourSoltani** [comment]
Thank you! 
I think there is some advancement..
But it stopped.. here is what I found
![Screenshot from 2022-10-12 16-53-49](https://user-images.githubusercontent.com/57375012/195395328-c14ee402-f7f7-4030-8015-3191252b75fd.png)

**Comment by jacobderosa** [comment]
@NourSoltani this often happens when there is insufficient GPU memory to run the VisSat step. There are ways to lower the GPU requirements if you are interested, as well as running VisSat with CPUs instead of GPUs (this will take much longer). Or if you already have a point cloud, there is an option to start Danesfield with that cloud instead of generating one.

**Comment by mleotta** [comment]
You could also try a different site or manually shrink the specified region of interest for Jacksonville to cover a smaller areas.  Jacksonville is the largest of our test datasets.  Larger sites will require more GPU memory.  We don't currently have tiling implemented to break the problem into smaller subproblems.  What GPU hardware are you using?

**Comment by NourSoltani** [comment]
@mleotta  @jacobderosa  We have a Quadro RTX 6000 with 24 GB of GPU memory..
So I think it is sufficient.. isn't it?

**Comment by mleotta** [comment]
Yeah, I think 24GB should be enough.  Looking closer, this error doesn't look like a GPU memory issue.  It looks like VisSat is trying to compute a `np.percentile` on and empty `z_values` on line 99 of `VisSatSatelliteStereo/reparam_depth.py`.  @jacobderosa can you help debug why `z_values` could be empty?  Those processing times for previous steps look very quick.  Maybe it's not actually finding the images?

**Comment by jacobderosa** [comment]
I recommend checking the log files for the clean_data and crop_image steps. You can find them at outdir/vissat/logs. They will have more clues as to what's going wrong here. Post them here and I can look through them.

**Comment by NourSoltani** [comment]
Oh Okay! I understand you.
You can find below all the log files.
[log_sfm_perspective.txt](https://github.com/Kitware/Danesfield/files/9809120/log_sfm_perspective.txt)
[log_reparam_depth.txt](https://github.com/Kitware/Danesfield/files/9809121/log_reparam_depth.txt)
[log_derive_approx.txt](https://github.com/Kitware/Danesfield/files/9809122/log_derive_approx.txt)
[log_crop_image.txt](https://github.com/Kitware/Danesfield/files/9809123/log_crop_image.txt)
[log_clean_data.txt](https://github.com/Kitware/Danesfield/files/9809125/log_clean_data.txt)
